version: '2.1'
services:
    ######################################################
    # SPARK SERVICES
    ######################################################
    
    spark-base:
        build:
            context: ./spark-base
            dockerfile: Dockerfile
        image: spark-base:latest

    spark-master:
        build: ./spark-master
        restart: always
        container_name: spark-master
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        ports:
            - "32766:8082"
            - "32765:7077"
        healthcheck:
            test: [ "CMD", "nc", "-z", "spark-master", "8082" ]
            timeout: 45s
            interval: 10s
            retries: 10

    spark-worker:
        build: ./spark-worker
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        depends_on:
            - spark-master
        ports:
            - "32764:8081"
        healthcheck:
            test: [ "CMD", "nc", "-z", "spark-worker", "8081" ]
            timeout: 45s
            interval: 10s
            retries: 10